KRSolutions\Bundle\KRUserBundle\Entity\User:
    type: entity
    table: kruser_users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
